// Iwpag Company All Rights Reserved

#pragma once

#include "NativeGameplayTags.h"

namespace WarriorGameplayTags
{
	//** Input Tags **/

	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_EquipAxe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_UnequipAxe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_LightAttack_Axe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_HeavyAttack_Axe);

	//** Player Tags **/
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Equip_Axe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Unequip_Axe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Light_Axe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_Attack_Heavy_Axe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Ability_HitPause);


	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Weapon_Axe);

	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Equip_Axe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_Unequip_Axe);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Event_HitPause);

	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_Status_JumpToFinisher);

	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Light);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Player_SetByCaller_AttackType_Heavy);


	//** Enemy Tags **/
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Melee);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Ability_Ranged);

	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Enemy_Weapon);


	//** Shared Tags **/

	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_HitReact);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Ability_Death);


	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_MeleeHit);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Event_HitReact);


	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_SetByCaller_BaseDamage);
	WARRIOROFTHEWORLD_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Shared_Status_Dead);






}